[theme]
primaryColor="#FF4B4B"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

[server]
maxUploadSize = 200
enableXsrfProtection = false
# Tắt file watcher để tránh lỗi path confusion
fileWatcherType = "none"
# Hoặc dùng "poll" nếu vẫn muốn auto-reload
# fileWatcherType = "poll"
